### ISSUE TITLE
Avoid overriding maven deploy phase

### ISSUE THREAD

**Issue by drissamri** [LinguaRobot/aws-cdk-maven-plugin-example#1]
I don't know much on Maven plugins but is it possible to avoid overriding the deploy stage of maven and instead adding a new phase/prefix so both can exist? 

In our pipeline we do `mvn deploy` to release all artifacts to Nexus/Artifactory/AWS Code Artifact instead of actually doing the deployment (also for our CDK code) so we can release a specific package of CDK and our app code. Hopefully this can co-exist to a `mvn cdk:deploy` or something along these lines?

**Comment by RoKish** [comment]
Hi Driss,

Thank you for your question and sorry for the long time with no reply.

There're a couple of options you can achieve this.

1. I believe the best option, that is commonly used for cases like this, is to create a special profile for the application deployment. In this case, the goals will remain bound to the default phases (which are `package` for `synth` goal, `deploy` for `bootstrap` and `deploy` goals), but they will be run only if the profile is active. 
```xml
<properties>
    <skipDeployment>true</skipDeployment>
    ...
</properties>

<profiles>
    <profile>
        <id>deployment</id>
        <properties>
            <skipDeployment>false</skipDeployment>
        </properties>
    </profile>
    ...
</profiles>

<build>
    <plugins>
        <plugin>
            <groupId>io.linguarobot</groupId>
            <artifactId>aws-cdk-maven-plugin</artifactId>
            <version>0.0.7</version>
            <executions>
                <execution>
                    <id>deploy-cdk-app</id>
                    <goals>
                        <goal>synth</goal>
                        <goal>bootstrap</goal>
                        <goal>deploy</goal>
                    </goals>
                    <configuration>
                        <skip>${skipDeployment}</skip>
                        <app>com.myorg.ExampleApp</app>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
    ...
</build>
```

With the configuration above, to deploy a CDK application to an AWS environment  run `mvn clean deploy -Pdeployment`. If the `deployment` profile is not active, the execution of the goals will be skipped due to the `skip` flag (the flag was added in `0.0.7`, please make sure to use this version or above).

2. Another option is similar to what you're asking. You can invoke `synth`, `bootstrap` (may be omitted), and `deploy` goals manually from the command line. Just add the plugin definition to the `build` section:

```xml
<build>
    <plugins>
        <plugin>
            <groupId>io.linguarobot</groupId>
            <artifactId>aws-cdk-maven-plugin</artifactId>
            <version>0.0.7</version>
        </plugin>
        ...
    </plugins>
</build>
```

Then, you should be able to deploy the CDK application defined in `com.myorg.ExampleApp` using the following command:
```
mvn clean install aws-cdk:synth aws-cdk:bootstrap aws-cdk:deploy -Daws.cdk.app=com.myorg.ExampleApp
```

You can also configure the plugin in the `<configuration>` section to not pass the parameters using `-D`:
```xml
<build>
    <plugins>
        <plugin>
            <groupId>io.linguarobot</groupId>
            <artifactId>aws-cdk-maven-plugin</artifactId>
            <version>0.0.7</version>
            <configuration>
                <app>com.myorg.ExampleApplication</app>
            </configuration>
        </plugin>
    </plugins>
</build>
```

```
mvn clean install aws-cdk:synth aws-cdk:bootstrap aws-cdk:deploy
```
